#!/usr/bin/env bash
#
# PyDM Native Messaging Host Installer
#
# Installs the native messaging host manifest for Chrome/Chromium/Brave and/or Firefox
# so the browser extension can communicate with the PyDM application.
#
# Usage:
#   ./install.sh [--chrome] [--firefox] [--uninstall]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
HOST_NAME="com.pydm.native"

# Browser native messaging host directories
CHROME_NMH_DIR="$HOME/.config/google-chrome/NativeMessagingHosts"
CHROMIUM_NMH_DIR="$HOME/.config/chromium/NativeMessagingHosts"
BRAVE_NMH_DIR="$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
FIREFOX_NMH_DIR="$HOME/.mozilla/native-messaging-hosts"

install_chrome=false
install_firefox=false
uninstall=false

# Parse arguments
for arg in "$@"; do
    case "$arg" in
        --chrome)   install_chrome=true ;;
        --firefox)  install_firefox=true ;;
        --uninstall) uninstall=true ;;
        --help|-h)
            echo "Usage: $0 [--chrome] [--firefox] [--uninstall]"
            echo ""
            echo "  --chrome     Install for Chrome/Chromium/Brave"
            echo "  --firefox    Install for Firefox"
            echo "  --uninstall  Remove installed manifests"
            echo ""
            echo "If no flag is specified, installs for all detected browsers."
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            exit 1
            ;;
    esac
done

# Default: install for all
if ! $install_chrome && ! $install_firefox; then
    install_chrome=true
    install_firefox=true
fi

# Find Python — use venv if available, else system python
find_python() {
    if [ -f "$PROJECT_DIR/venv/bin/python3" ]; then
        echo "$PROJECT_DIR/venv/bin/python3"
    elif [ -f "$PROJECT_DIR/.venv/bin/python3" ]; then
        echo "$PROJECT_DIR/.venv/bin/python3"
    else
        echo "python3"
    fi
}

# Create the wrapper script
create_wrapper() {
    local wrapper_path="$PROJECT_DIR/native_host/pydm_native_host.sh"
    local python_path
    python_path=$(find_python)

    cat > "$wrapper_path" << WRAPPER_EOF
#!/usr/bin/env bash
# PyDM Native Messaging Host wrapper
# Auto-generated by install.sh — do not edit manually
exec "$python_path" -c "
import sys
sys.path.insert(0, '$PROJECT_DIR')
from pydm.native_messaging import main
main()
" "\$@"
WRAPPER_EOF
    chmod +x "$wrapper_path"
    echo "$wrapper_path"
}

# Generate the manifest JSON
generate_manifest() {
    local wrapper_path="$1"
    local manifest_type="$2"  # "chrome" or "firefox"

    if [ "$manifest_type" = "firefox" ]; then
        cat << EOF
{
  "name": "$HOST_NAME",
  "description": "PyDM Native Messaging Host",
  "path": "$wrapper_path",
  "type": "stdio",
  "allowed_extensions": [
    "pydm@pydm.local"
  ]
}
EOF
    else
        cat << EOF
{
  "name": "$HOST_NAME",
  "description": "PyDM Native Messaging Host",
  "path": "$wrapper_path",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://pflmlgjlhcahdkphbimklhjahepkknec/"
  ]
}
EOF
    fi
}

install_for_dir() {
    local nmh_dir="$1"
    local manifest_content="$2"
    local browser_name="$3"

    if [ -d "$(dirname "$nmh_dir")" ] || [ "$browser_name" = "Chrome" ] || [ "$browser_name" = "Chromium" ]; then
        mkdir -p "$nmh_dir"
        echo "$manifest_content" > "$nmh_dir/$HOST_NAME.json"
        echo "✅ Installed for $browser_name: $nmh_dir/$HOST_NAME.json"
    else
        echo "⏭  $browser_name not detected, skipped"
    fi
}

uninstall_for_dir() {
    local nmh_dir="$1"
    local browser_name="$2"
    local manifest_file="$nmh_dir/$HOST_NAME.json"

    if [ -f "$manifest_file" ]; then
        rm "$manifest_file"
        echo "🗑  Removed from $browser_name: $manifest_file"
    else
        echo "ℹ  Did not exist in $browser_name"
    fi
}

echo ""
echo "═══════════════════════════════════════"
echo "  PyDM Native Messaging Host Installer"
echo "═══════════════════════════════════════"
echo ""

if $uninstall; then
    echo "Uninstalling..."
    if $install_chrome; then
        uninstall_for_dir "$CHROME_NMH_DIR" "Chrome"
        uninstall_for_dir "$CHROMIUM_NMH_DIR" "Chromium"
        uninstall_for_dir "$BRAVE_NMH_DIR" "Brave"
    fi
    if $install_firefox; then
        uninstall_for_dir "$FIREFOX_NMH_DIR" "Firefox"
    fi
    rm -f "$PROJECT_DIR/native_host/pydm_native_host.sh"
    rm -f "$HOME/.local/share/applications/pydm.desktop"
    echo ""
    echo "✅ Uninstallation complete"
else
    echo "Installing..."
    echo ""

    # Create wrapper script
    wrapper_path=$(create_wrapper)
    echo "📝 Wrapper created: $wrapper_path"
    echo "🐍 Python: $(find_python)"
    echo ""

    if $install_chrome; then
        manifest=$(generate_manifest "$wrapper_path" "chrome")
        install_for_dir "$CHROME_NMH_DIR" "$manifest" "Chrome"
        install_for_dir "$CHROMIUM_NMH_DIR" "$manifest" "Chromium"
        install_for_dir "$BRAVE_NMH_DIR" "$manifest" "Brave"
    fi

    if $install_firefox; then
        manifest=$(generate_manifest "$wrapper_path" "firefox")
        install_for_dir "$FIREFOX_NMH_DIR" "$manifest" "Firefox"
    fi

    # Create Desktop Entry
    DESKTOP_ENTRY="$HOME/.local/share/applications/pydm.desktop"
    mkdir -p "$(dirname "$DESKTOP_ENTRY")"
    cat > "$DESKTOP_ENTRY" << EOF
[Desktop Entry]
Name=PyDM
Comment=Python Download Manager
Exec=$(find_python) -m pydm.main
Icon=$PROJECT_DIR/assets/icon.png
Terminal=false
Type=Application
Categories=Network;FileTransfer;
Path=$PROJECT_DIR
EOF
    chmod +x "$DESKTOP_ENTRY"
    echo "🖥️  Desktop shortcut created: $DESKTOP_ENTRY"

    echo ""
    echo "═══════════════════════════════════════"
    echo "  ✅ Installation complete"
    echo ""
    echo "  Next steps:"
    echo "  1. Load the extension in your browser:"
    echo "     chrome://extensions → Developer mode → Load unpacked"
    echo "     Select the directory: $PROJECT_DIR/browser_extension/"
    echo ""
    echo "  Communication has been automatically linked via static ID."
    echo "  You can now launch PyDM from your Linux app menu!"
    echo "═══════════════════════════════════════"
fi
echo ""
