@echo off
REM PyDM Native Messaging Host wrapper for Windows
REM Auto-generated by install.ps1 — do not edit manually

REM Determine script directory
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."

REM Use venv Python if it exists, otherwise system Python
if exist "%PROJECT_DIR%\venv\Scripts\python.exe" (
    set "PYTHON=%PROJECT_DIR%\venv\Scripts\python.exe"
) else if exist "%PROJECT_DIR%\.venv\Scripts\python.exe" (
    set "PYTHON=%PROJECT_DIR%\.venv\Scripts\python.exe"
) else (
    set "PYTHON=python"
)

"%PYTHON%" -c "import sys; sys.path.insert(0, r'%PROJECT_DIR%'); from pydm.native_messaging import main; main()"
